### ISSUE TITLE
Parse error /  Typescript error: "Unable to parse Trans component with the content"

### ISSUE THREAD

**Issue by Bnaya** [i18next/i18next-scanner#128]
#### Version
- i18next: 14.0.1
- i18next-scanner: 2.9.1
- react-i18next: 9.0.10

#### Configuration
```js
var fs = require('fs')
var chalk = require('chalk')
const typescript = require('typescript')
const path = require('path')

module.exports = {
  options: {
    debug: true,
    func: {
      list: ['i18next.t', 'i18n.t'],
      extensions: ['.ts', '.tsx'],
    },
    trans: {
      component: 'Trans',
      i18nKey: 'i18nKey',
      defaultsKey: 'defaults',
      extensions: ['.ts', '.tsx'],
      fallbackKey: function(ns, value) {
        // Returns a hash value as the fallback key
        return sha1(value)
      },
    },
    lngs: ['en', 'fr'],
    ns: ['locale', 'resource'],
    defaultLng: 'en',
    defaultNs: 'resource',
    defaultValue: '__STRING_NOT_TRANSLATED__',
    resource: {
      loadPath: 'src/locales/{{lng}}/{{ns}}.json',
      savePath: 'src/locales/{{lng}}/{{ns}}.json',
      jsonIndent: 2,
      lineEnding: '\n',
    },
    nsSeparator: false, // namespace separator
    keySeparator: false, // key separator
    interpolation: {
      prefix: '{{',
      suffix: '}}',
    },
  },
  // // https://github.com/i18next/i18next-scanner/issues/88#issuecomment-452168905
  // // with mods
  // transform(file, enc, done) {
  //   const extension = path.extname(file.path)
  //   const parser = this.parser
  //   let content = fs.readFileSync(file.path, enc)

  //   debugger

  //   if (extension === '.ts' || extension === '.tsx') {
  //     content = typescript.transpileModule(content, {
  //       compilerOptions: {},
  //       fileName: path.basename(file.path),
  //     }).outputText
  //   }

  //   if (parser.options.attr.extensions.indexOf(extension) !== -1) {
  //     parser.parseAttrFromString(content)
  //   }

  //   if (parser.options.func.extensions.indexOf(extension) !== -1) {
  //     parser.parseFuncFromString(content)
  //   }

  //   done()
  // },
  // transform: function customTransform(file, enc, done) {
  //   'use strict'
  //   const parser = this.parser
  //   const content = fs.readFileSync(file.path, enc)
  //   let count = 0

  //   parser.parseFuncFromString(
  //     content,
  //     { list: ['i18next._', 'i18next.__'] },
  //     (key, options) => {
  //       parser.set(
  //         key,
  //         Object.assign({}, options, {
  //           nsSeparator: false,
  //           keySeparator: false,
  //         })
  //       )
  //       ++count
  //     }
  //   )

  //   if (count > 0) {
  //     console.log(
  //       `i18next-scanner: count=${chalk.cyan(count)}, file=${chalk.yellow(
  //         JSON.stringify(file.relative)
  //       )}`
  //     )
  //   }

  //   done()
  // },
}

```

When running, im getting this kind of error for all of my files
Error: 
```i18next-scanner: Unable to parse Trans component with the content
{ SyntaxError: Unexpected token (17:1)
    at Object.pp$4.raise (/***node_modules/acorn/dist/acorn.js:2807:13)
    at Object.pp.unexpected (/***node_modules/acorn/dist/acorn.js:688:8)
    at Object.pp.expect (/***node_modules/acorn/dist/acorn.js:682:26)
    at Object.pp$3.parseParenAndDistinguishExpression (/***node_modules/acorn/dist/acorn.js:2299:38)
    at Object.pp$3.parseExprAtom (/***node_modules/acorn/dist/acorn.js:2234:41)
    at Object.parseExprAtom (/***node_modules/acorn-dynamic-import/lib/index.js:75:117)
    at Object.parseExprAtom (/***node_modules/acorn-import-meta/index.js:17:75)
    at Object.parseExprAtom (/***node_modules/acorn-class-fields/index.js:155:26)
    at Object.parseExprAtom (/***node_modules/acorn-static-class-features/index.js:219:26)
    at Object.parseExprAtom (/***node_modules/acorn-private-methods/index.js:151:26)
  pos: 350,
  loc: Position { line: 17, column: 1 },
  raisedAt: 351 }
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core/styles'
import React from 'react'
import { I18nextProvider } from 'react-i18next'
import i18n from '../i18n'

const theme = createMuiTheme({
  typography: {
    useNextVariants: true,
  },
  palette: {
    type: 'dark',
  },
})

export const WrapRootElementCommon = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <I18nextProvider i18n={i18n}>
      <MuiThemeProvider theme={theme}>{children}</MuiThemeProvider>
    </I18nextProvider>
  )
}

```

**Comment by daliusd** [comment]
You should compile your typescript to javascript before running i18next-scanner.

**Comment by Bnaya** [comment]
I'm working with webpack,
i don't have any build step that applicable in that way (yet, and i really hope to avoid it)

**Comment by Bnaya** [comment]
i've added a transpiration step before running the scanner.
i hope it will work properly

**Comment by nesinervink** [comment]
@Bnaya would you care sharing a snippet of your `transform` function?
