### ISSUE TITLE
Fails scanning my files: Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by BjoernRave** [i18next/i18next-scanner#174]
It was working flawlessly before for me, but at some point, not sure what changed I get the following error when trying to run `i18next-scanner`:

`sudo` doesn't help
```
internal/fs/utils.js:220
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:506:3)
    at tryReadSync (fs.js:331:20)
    at Object.readFileSync (fs.js:368:19)
    at DestroyableTransform._transform (/Users/bjoern/projects/inventhora/frontend/node_modules/i18next-scanner/lib/index.js:26:34)
    at DestroyableTransform.Transform._read (/Users/bjoern/projects/inventhora/frontend/node_modules/i18next-scanner/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write (/Users/bjoern/projects/inventhora/frontend/node_modules/i18next-scanner/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/bjoern/projects/inventhora/frontend/node_modules/i18next-scanner/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Users/bjoern/projects/inventhora/frontend/node_modules/i18next-scanner/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DestroyableTransform.Writable.write (/Users/bjoern/projects/inventhora/frontend/node_modules/i18next-scanner/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DestroyableTransform.ondata (/Users/bjoern/projects/inventhora/frontend/node_modules/readable-stream/lib/_stream_readable.js:619:20) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
error Command failed with exit code 1.
```

#### Version
- next-translate: <i>0.8.0</i> (uses same `t('namespace:key')` syntax)
- i18next-scanner: <i>2.10.3</i>

#### Configuration
```js
var fs = require('fs')
var chalk = require('chalk')

module.exports = {
  input: ['./**/*.{ts,tsx}', '!**/node_modules/**'],
  output: './',
  options: {
    func: {
      list: ['t'],
      extensions: ['.ts', '.tsx']
    },
    lngs: ['en', 'es', 'pt'],
    ns: ['common', 'table', 'forms', 'account'],
    defaultLng: 'en',
    defaultNs: 'common',
    defaultValue: '',
    resource: {
      loadPath: 'public/locales/{{lng}}/{{ns}}.json',
      savePath: 'public/locales/{{lng}}/{{ns}}.json',
      jsonIndent: 2,
      lineEnding: '\n'
    },
    nsSeparator: ':', // namespace separator
    keySeparator: false, // key separator
    interpolation: {
      prefix: '{{',
      suffix: '}}'
    }
  },
  transform: function customTransform(file, enc, done) {
    'use strict'
    const parser = this.parser
    const content = fs.readFileSync(file.path, enc)
    let count = 0

    parser.parseFuncFromString(
      content,
      { list: ['i18next._', 'i18next.__'] },
      (key, options) => {
        parser.set(
          key,
          Object.assign({}, options, {
            nsSeparator: false,
            keySeparator: false
          })
        )
        ++count
      }
    )

    if (count > 0) {
      console.log(
        `i18next-scanner: count=${chalk.cyan(count)}, file=${chalk.yellow(
          JSON.stringify(file.relative)
        )}`
      )
    }

    done()
  }
}
```

**Comment by BjoernRave** [comment]
I looked around a little and I think there is a solution described here: https://github.com/jonschlinkert/copy/issues/24

**Comment by fillon** [comment]
@BjoernRave I have the same problem. Did you find a solution?

**Comment by fillon** [comment]
```js
module.exports = {
    input: [
        'application/**/*.php',
        'src/**/*.{js,jsx}',
        'template/**/*.php',
        // Use ! to filter out files or directories
        '!src/**/*.test.{js,jsx}',
        '!**/node_modules/**'
    ],
    output: './',
    options: {
        debug: true,
        sort: true,
        func: {
            list: ['i18next.t', 'i18n.t', 't', '_'],
            extensions: ['.js', '.jsx', '.php']
        },
        trans: {
            component: 'Trans',
            extensions: ['.js', '.jsx'],
            defaultsKey: '-',
            fallbackKey: true
        },
        removeUnusedKeys: true,
        lngs: [
            'ar',
            'da',
            'de',
            'en',
            'es',
            'fi',
            'fr',
            'hi',
            'id',
            'it',
            'ja',
            'ko',
            'ms',
            'nl',
            'no',
            'pt',
            'ru',
            'sv',
            'th',
            'tl',
            'tr',
            'vi',
            'zh'
        ],
        defaultLng: 'en',
        defaultValue: function(lng, ns, key) {
            return key;
        },
        resource: {
            loadPath: 'htdocs/locales/{{ns}}_{{lng}}.json',
            savePath: 'htdocs/locales/{{ns}}_{{lng}}.json',
            jsonIndent: 4
        },
        nsSeparator: false,
        keySeparator: false,
        interpolation: {
            prefix: '{{',
            suffix: '}}'
        }
    }
};
```

**Comment by fillon** [comment]
Found it... one of the subdirectories was ending with 'js'.

**Comment by coderfin** [comment]
I was having the same issue for the same reason as @fillon.  I needed a subdirectory that ended in `.js` though because I was manually mocking a node_modules module that had a folder ending in `.js`.  

A tip for devs publishing packages out there: Do not name your folders `{name}.js`.  It just causes so many weird things.

Anyway, I use this as my npm script:
`i18next-scanner --output src/locales 'src/**/*.js' '!**/__mocks__/**/*'` and it works well.

**Comment by boredland** [comment]
How did you people find the violating files? In my case it doesn't seem to be a directory with `.` in it, so I wonder what it could be...

**Comment by etrevathan** [comment]
I'm getting the same error associated with BigQuery Runner. No issues and now this and I have no idea what is causing it.
